/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-tertiary-container": "#ffdedf",
                "tertiary-fixed-dim": "#ffb2b7",
                "on-primary": "#ffffff",
                "on-secondary": "#ffffff",
                "surface-container-highest": "#d3e4fe",
                "on-primary-fixed": "#001b3d",
                "on-secondary-container": "#00714d",
                "secondary": "#006c49",
                "outline-variant": "#c1c6d4",
                "on-error": "#ffffff",
                "secondary-fixed": "#6ffbbe",
                "on-primary-fixed-variant": "#00468a",
                "on-surface-variant": "#414752",
                "background": "#f8f9ff",
                "on-secondary-fixed": "#002113",
                "outline": "#727783",
                "tertiary-fixed": "#ffdadb",
                "on-primary-container": "#dbe6ff",
                "inverse-primary": "#a8c8ff",
                "primary-fixed": "#d6e3ff",
                "inverse-surface": "#213145",
                "surface-bright": "#f8f9ff",
                "surface-variant": "#d3e4fe",
                "on-tertiary-fixed-variant": "#92002a",
                "error-container": "#ffdad6",
                "on-surface": "#0b1c30",
                "on-background": "#0b1c30",
                "on-secondary-fixed-variant": "#005236",
                "surface-container-low": "#eff4ff",
                "primary": "#004e99",
                "surface-tint": "#005eb5",
                "surface-container-high": "#dce9ff",
                "secondary-fixed-dim": "#4edea3",
                "primary-container": "#0a66c2",
                "surface-dim": "#cbdbf5",
                "tertiary-container": "#c81a42",
                "error": "#ba1a1a",
                "tertiary": "#a0002f",
                "secondary-container": "#6cf8bb",
                "surface": "#f8f9ff",
                "on-error-container": "#93000a",
                "inverse-on-surface": "#eaf1ff",
                "primary-fixed-dim": "#a8c8ff",
                "on-tertiary-fixed": "#40000d",
                "surface-container-lowest": "#ffffff",
                "surface-container": "#e5eeff",
                "on-tertiary": "#ffffff",
            },
            fontFamily: {
                headline: ["Inter", "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                "2xl": "1rem",
                full: "9999px",
            },
        },
    },
    plugins: [],
};
