import { useEffect, useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';

import { getOverviewReport, generateReport, getReportHistory } from '../../services/admin';
import type { ReportOverview, PaymentStatus, UserRole } from '../../types/api';
import { exportRowsToCsv } from '../../utils/export';
import { formatMoney } from '../../utils/format';

type ReportsWorkspaceProps = {
  token: string;
  role: UserRole;
  onError: (message: string) => void;
};

export function ReportsWorkspace({ token, role, onError }: ReportsWorkspaceProps) {
  const navigate = useNavigate();
  const isAdmin = role === 'ADMIN';
  const isAccounts = role === 'ACCOUNTS';
  const [report, setReport] = useState<ReportOverview | null>(null);
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<PaymentStatus | ''>('');
  const [methodFilter, setMethodFilter] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [academicYearFilter, setAcademicYearFilter] = useState('');
  const [termFilter, setTermFilter] = useState('');
  const [semesterFilter, setSemesterFilter] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize] = useState(25);

  async function loadReport(filters?: any) {
    setLoading(true);
    try {
      const [data, historyData] = await Promise.all([
        getOverviewReport(token, filters),
        getReportHistory(token)
      ]);
      setReport(data);
      setHistory(historyData);
    } catch (error) {
      onError(error instanceof Error ? error.message : 'Failed to load report overview');
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerateSnapshot() {
    if (!report) return;
    setGenerating(true);
    try {
      const title = `Financial Report - ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`;
      const type = academicYearFilter || termFilter || semesterFilter ? 'PERIODIC' : 'GENERAL';
      
      await generateReport(token, {
        title,
        reportType: type,
        filters: {
          startDate: startDate || undefined,
          endDate: endDate || undefined,
          academicYear: academicYearFilter || undefined,
          term: termFilter || undefined,
          semester: semesterFilter || undefined,
          status: statusFilter || undefined,
          method: methodFilter || undefined
        }
      });
      await loadReport({
        status: statusFilter || undefined,
        method: methodFilter || undefined,
        startDate: startDate || undefined,
        endDate: endDate || undefined,
        academicYear: academicYearFilter || undefined,
        term: termFilter || undefined,
        semester: semesterFilter || undefined,
        limit: pageSize,
        offset: (currentPage - 1) * pageSize,
      });
    } catch (error) {
      onError(error instanceof Error ? error.message : 'Failed to generate official snapshot');
    } finally {
      setGenerating(false);
    }
  }

  function downloadSnapshot(snapshot: any) {
    const data = snapshot.data as ReportOverview;
    if (!data) return;

    exportRowsToCsv(
      `snapshot-${snapshot.id}.csv`,
      ['Section', 'Label', 'Value'],
      [
        ['Metadata', 'Report ID', snapshot.id],
        ['Metadata', 'Title', snapshot.title],
        ['Metadata', 'Generated By', `${snapshot.user?.firstName || ''} ${snapshot.user?.lastName || ''}`],
        ['Metadata', 'Date', snapshot.createdAt],
        ['Summary', 'Students Count', data.summary.studentsCount],
        ['Summary', 'Approved Payments', data.summary.approvedPayments],
        ['Summary', 'Total Approved Amount', data.summary.totalApprovedAmount],
        ...Object.entries(data.paymentMethodBreakdown).map(([m, a]) => ['Payment Method', m, a]),
      ]
    );
  }

  useEffect(() => {
    void loadReport({
      status: statusFilter || undefined,
      method: methodFilter || undefined,
      startDate: startDate || undefined,
      endDate: endDate || undefined,
      academicYear: academicYearFilter || undefined,
      term: termFilter || undefined,
      semester: semesterFilter || undefined,
      limit: pageSize,
      offset: (currentPage - 1) * pageSize,
    });
  }, [token, statusFilter, methodFilter, startDate, endDate, academicYearFilter, termFilter, semesterFilter, currentPage]);

  const filteredPayments = useMemo(() => {
    if (!report) return [];
    if (!searchQuery.trim()) return report.recentPayments;

    const query = searchQuery.toLowerCase();
    return report.recentPayments.filter(p =>
      p.student?.firstName.toLowerCase().includes(query) ||
      p.student?.lastName.toLowerCase().includes(query) ||
      p.student?.studentCode.toLowerCase().includes(query) ||
      p.receiptNumber?.toLowerCase().includes(query)
    );
  }, [report, searchQuery]);

  const verificationRate = report ?
    Math.round((report.summary.approvedPayments / (report.summary.approvedPayments + report.summary.pendingPayments + report.summary.rejectedPayments || 1)) * 1000) / 10 : 0;

  function handleExportReport() {
    if (!report) return;
    exportRowsToCsv(
      'report-overview.csv',
      ['Section', 'Label', 'Value'],
      [
        ['Summary', 'Students Count', report.summary.studentsCount],
        ['Summary', 'Pending Payments', report.summary.pendingPayments],
        ['Summary', 'Approved Payments', report.summary.approvedPayments],
        ['Summary', 'Rejected Payments', report.summary.rejectedPayments],
        ['Summary', 'Total Approved Amount', report.summary.totalApprovedAmount],
        ...Object.entries(report.paymentMethodBreakdown).map(([method, amount]) => ['Payment Method', method, amount]),
        ...Object.entries(report.monthlyCollections).map(([month, amount]) => ['Monthly Collection', month, amount]),
      ],
    );
  }

  function handleExportRecentPayments() {
    if (!report?.recentPayments.length) return;
    exportRowsToCsv(
      'recent-payments.csv',
      ['Student Name', 'Student Code', 'Amount', 'Method', 'Status', 'Year', 'Term', 'Semester', 'Verified By', 'Approved By', 'Payment Date', 'Submitted At'],
      report.recentPayments.map((payment) => [
        `${payment.student?.firstName || ''} ${payment.student?.lastName || ''}`.trim(),
        payment.student?.studentCode || '',
        payment.amount,
        payment.method,
        payment.status,
        payment.academicYear || '',
        payment.term || '',
        payment.semester || '',
        payment.verifier?.email || 'N/A',
        payment.reviewer?.email || 'N/A',
        payment.paymentDate,
        payment.submittedAt,
      ]),
    );
  }

  const getMonthName = (monthKey: string) => {
    if (!monthKey.includes('-')) return monthKey;
    const [year, month] = monthKey.split('-');
    const date = new Date(parseInt(year), parseInt(month) - 1);
    return date.toLocaleString('default', { month: 'short' });
  };

  return (
    <div className="space-y-10 animate-in fade-in duration-700">
      {/* Header Section */}
      <section className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 bg-white/40 p-8 rounded-[2rem] border border-white/40 shadow-sm backdrop-blur-md">
        <div>
          <span className="text-primary font-black tracking-[0.08em] uppercase text-[12px]">Analytics Portfolio</span>
          <h1 className="text-4xl font-black tracking-tighter text-slate-900 mt-2">Reporting and collections.</h1>
        </div>
        
        {isAccounts ? (
          <div className="flex gap-4">
            <button
              disabled={generating}
              onClick={handleGenerateSnapshot}
              className="flex items-center gap-2 px-6 py-3.5 bg-slate-900 hover:bg-slate-800 text-white font-black text-[12px] uppercase tracking-widest rounded-2xl shadow-xl shadow-slate-200 transition-all active:scale-95 disabled:opacity-50"
            >
              <span className="material-symbols-outlined text-[18px]">auto_awesome</span>
              {generating ? 'Processing...' : 'Generate Official Snapshot'}
            </button>
            <button
              onClick={handleExportReport}
              className="flex items-center gap-2 px-6 py-3.5 bg-white hover:bg-slate-50 text-slate-900 font-black text-[12px] uppercase tracking-widest rounded-2xl border border-slate-200 transition-all active:scale-95"
            >
              <span className="material-symbols-outlined text-[18px]">export_notes</span>
              Quick Export
            </button>
          </div>
        ) : (
          <div className="flex flex-col items-end">
            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest bg-slate-100 px-3 py-1 rounded-lg">View-Only Monitor</span>
          </div>
        )}
      </section>

      {/* KPI Grid */}
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {/* Total Collections */}
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 flex flex-col justify-between min-h-[180px] relative overflow-hidden group shadow-sm hover:shadow-xl transition-all duration-500">
          <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
            <span className="material-symbols-outlined text-7xl text-primary">account_balance_wallet</span>
          </div>
          <div>
            <span className="text-[12px] font-black tracking-widest text-slate-500 uppercase mb-2 block tracking-wider">Total Collections</span>
            <h2 className="text-3xl font-black tracking-tighter text-primary">
              {loading ? '---' : formatMoney(report?.summary.totalApprovedAmount || 0)}
            </h2>
          </div>
          <div className="flex items-center gap-2 text-emerald-600 text-[11px] font-black uppercase tracking-widest">
            <span className="material-symbols-outlined text-sm">trending_up</span>
            <span>Stable growth cycle</span>
          </div>
        </div>

        {/* Pending Approvals */}
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 flex flex-col justify-between min-h-[180px] relative overflow-hidden group shadow-sm hover:shadow-xl transition-all duration-500">
          <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
            <span className="material-symbols-outlined text-7xl text-orange-500">pending_actions</span>
          </div>
          <div>
            <span className="text-[10px] font-black tracking-widest text-slate-400 uppercase mb-2 block">Pending Review</span>
            <h2 className="text-3xl font-black tracking-tighter text-slate-900">
              {loading ? '---' : (report?.summary.pendingPayments || 0).toLocaleString()}
            </h2>
          </div>
          <div className="flex items-center gap-2 text-orange-500 text-[10px] font-black uppercase tracking-widest">
            <span className="material-symbols-outlined text-sm">priority_high</span>
            <span>Awaiting verification</span>
          </div>
        </div>

        {/* Verification Rate */}
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 flex flex-col justify-between min-h-[180px] relative overflow-hidden group shadow-sm hover:shadow-xl transition-all duration-500">
          <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
            <span className="material-symbols-outlined text-7xl text-emerald-500">verified_user</span>
          </div>
          <div>
            <span className="text-[10px] font-black tracking-widest text-slate-400 uppercase mb-2 block">Verification Rate</span>
            <h2 className="text-3xl font-black tracking-tighter text-slate-900">{loading ? '---' : `${verificationRate}%`}</h2>
          </div>
          <div className="h-1.5 w-full bg-slate-50 rounded-full overflow-hidden mt-4">
            <div
              className="h-full bg-emerald-500 transition-all duration-1000"
              style={{ width: `${verificationRate}%` }}
            />
          </div>
        </div>

        {/* Total Students */}
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 flex flex-col justify-between min-h-[180px] relative overflow-hidden group shadow-sm hover:shadow-xl transition-all duration-500">
          <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
            <span className="material-symbols-outlined text-7xl text-slate-300">face</span>
          </div>
          <div>
            <span className="text-[10px] font-black tracking-widest text-slate-400 uppercase mb-2 block">Student Population</span>
            <h2 className="text-3xl font-black tracking-tighter text-slate-900">
              {loading ? '---' : (report?.summary.studentsCount || 0).toLocaleString()}
            </h2>
          </div>
          <div className="flex items-center gap-2 text-slate-400 text-[10px] font-black uppercase tracking-widest">
            <span className="material-symbols-outlined text-sm">group</span>
            <span>Active enrollments</span>
          </div>
        </div>
      </section>

      {/* Charts Section */}
      <section className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Collection Trends */}
        <div className="lg:col-span-2 overflow-hidden">
          <div className="flex justify-between items-center mb-10">
            <div>
              <h3 className="text-xl font-black tracking-tight text-slate-900">Collection Velocity</h3>
              <p className="text-[12px] font-black text-slate-500 uppercase tracking-widest mt-1">Monthly institutional cash-flow</p>
            </div>
            <div className="bg-slate-50 px-4 py-2 rounded-xl text-[11px] font-black text-slate-600 uppercase tracking-widest border border-slate-100">
              Session 2024/25
            </div>
          </div>

          <div className="h-[280px] w-full pt-6 relative">
            {report ? (
              (() => {
                const rawEntries = Object.entries(report.monthlyCollections);
                if (rawEntries.length === 0) return <div className="text-center text-slate-300 italic text-xs font-black uppercase tracking-widest h-full flex items-center justify-center">No Activity log</div>;

                const fullPaymentRatio = (report.installmentMetrics?.fullPaymentPercentage ?? 65) / 100;
                const installmentRatio = (report.installmentMetrics?.installmentPercentage ?? 35) / 100;

                let runningTotal = 0;
                const entries = rawEntries.map(([month, amt]) => {
                  runningTotal += amt;
                  return [month, runningTotal] as [string, number];
                });

                const maxAmt = Math.max(...entries.map(e => e[1]), 1);

                // Map the coordinates to an SVG 0-100 coordinate space
                const getX = (i: number) => (i / (entries.length - 1 || 1)) * 100;
                const getY = (amt: number) => Math.max(0, 100 - (amt / maxAmt) * 100);

                return (
                  <div className="flex flex-col h-full w-full relative">
                    {/* Legend */}
                    <div className="absolute -top-6 right-4 flex gap-4 z-10">
                      <div className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: '#00E676' }}></span><span className="text-[11.5px] font-black uppercase text-slate-500 tracking-wide">Full Payments ({report.installmentMetrics?.fullPaymentPercentage ?? 65}%)</span></div>
                      <div className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: '#2962FF' }}></span><span className="text-[11.5px] font-black uppercase text-slate-500 tracking-wide">Installments ({report.installmentMetrics?.installmentPercentage ?? 35}%)</span></div>
                    </div>

                    {/* SVG Line Graph */}
                    <div className="relative flex-1 w-full border-b border-slate-100">
                      <svg className="absolute inset-0 w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 100">
                        <defs>
                          <linearGradient id="gradientGreen" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="#00E676" stopOpacity="0.25" />
                            <stop offset="100%" stopColor="#00E676" stopOpacity="0" />
                          </linearGradient>
                          <linearGradient id="gradientBlue" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="#2962FF" stopOpacity="0.25" />
                            <stop offset="100%" stopColor="#2962FF" stopOpacity="0" />
                          </linearGradient>
                        </defs>

                        {/* Shaded Areas */}
                        <polygon points={`0,100 ${entries.map(([_, amt], i) => `${getX(i)},${getY(amt * fullPaymentRatio)}`).join(' ')} 100,100`} fill="url(#gradientGreen)" />
                        <polygon points={`0,100 ${entries.map(([_, amt], i) => `${getX(i)},${getY(amt * installmentRatio)}`).join(' ')} 100,100`} fill="url(#gradientBlue)" />

                        {/* Tracking Lines */}
                        <polyline
                          points={entries.map(([_, amt], i) => `${getX(i)},${getY(amt * fullPaymentRatio)}`).join(' ')}
                          fill="none" stroke="#00E676" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"
                        />
                        <polyline
                          points={entries.map(([_, amt], i) => `${getX(i)},${getY(amt * installmentRatio)}`).join(' ')}
                          fill="none" stroke="#2962FF" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"
                        />

                        {/* Interactive Data Nodes */}
                        {entries.map(([_, amt], i) => {
                          const x = getX(i);
                          const yFull = getY(amt * fullPaymentRatio);
                          const yInst = getY(amt * installmentRatio);
                          const isCompletedAndLast = i === entries.length - 1;

                          return (
                            <g key={i} className="group cursor-default">
                              {/* Full Payments Node */}
                              <circle
                                cx={x} cy={yFull} r="4" fill="#ffffff" stroke="#00E676" strokeWidth="2.5" vectorEffect="non-scaling-stroke"
                                className="transition-all duration-300 group-hover:r-[7]"
                              />
                              {/* Installments Node (turns green if last/completed) */}
                              <circle
                                cx={x} cy={yInst} r="4" fill="#ffffff" stroke={isCompletedAndLast ? "#00E676" : "#2962FF"} strokeWidth="2.5" vectorEffect="non-scaling-stroke"
                                className="transition-all duration-300 group-hover:r-[7]"
                              />

                              <text x={x} y={yFull - 8} textAnchor="middle" fontSize="4.5" fill="#00E676" className="opacity-0 group-hover:opacity-100 font-black transition-opacity">
                                {formatMoney(amt * fullPaymentRatio)}
                              </text>
                              <text x={x} y={yInst - 8} textAnchor="middle" fontSize="4.5" fill={isCompletedAndLast ? "#00E676" : "#2962FF"} className="opacity-0 group-hover:opacity-100 font-black transition-opacity">
                                {formatMoney(amt * installmentRatio)}
                              </text>
                            </g>
                          );
                        })}
                      </svg>
                    </div>

                    {/* Timeline Axis */}
                    <div className="relative h-8 mt-4 w-full text-left">
                      {entries.map(([month], i) => {
                        const alignClass = i === 0 ? "text-left" : i === entries.length - 1 ? "text-right" : "text-center";
                        return (
                          <div
                            key={i}
                            className={`absolute w-12 text-[11px] font-black tracking-widest uppercase text-slate-500 -translate-x-1/2 ${alignClass}`}
                            style={{ left: `${getX(i)}%`, transform: i === 0 ? 'translateX(0)' : i === entries.length - 1 ? 'translateX(-100%)' : 'translateX(-50%)' }}
                          >
                            {getMonthName(month)}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                );
              })()
            ) : (
              <div className="w-full h-full flex items-center justify-center text-slate-300 italic text-xs uppercase font-black tracking-widest">Generating Trend Matrix...</div>
            )}
          </div>
        </div>

        {/* Channel Distribution */}
        <div className="flex flex-col">
          <h3 className="text-xl font-black tracking-tight text-slate-900 mb-1">Channel Mix</h3>
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-10">Payment lifecycle breakdown</p>

          <div className="relative w-44 h-44 mx-auto mb-10 group">
            <div className="absolute inset-0 rounded-full border-[14px] border-emerald-500" style={{ clipPath: 'polygon(50% 50%, 50% 0, 100% 0, 100% 100%, 0 100%, 0 0, 50% 0)' }}></div>
            <div className="absolute inset-0 rounded-full border-[14px] border-primary/20" style={{ clipPath: 'polygon(50% 50%, 50% 0, 100% 0, 100% 20%, 50% 50%)' }}></div>
            <div className="absolute inset-4 rounded-full bg-white flex flex-col items-center justify-center text-center shadow-inner">
              <span className="text-2xl font-black text-slate-900">
                {loading ? '--' : report?.summary.studentsCount}
              </span>
              <span className="text-[12px] uppercase font-black text-slate-500 tracking-widest">Students</span>
            </div>
          </div>

          <div className="space-y-4 flex-grow">
            {report ? Object.entries(report.paymentMethodBreakdown).map(([method, amount], i) => (
              <div key={method} className="flex justify-between items-center group cursor-default">
                <div className="flex items-center gap-3">
                  <span className={`w-2.5 h-2.5 rounded-full ${['bg-emerald-500', 'bg-primary', 'bg-slate-900', 'bg-slate-200'][i % 4]}`}></span>
                  <span className="text-[12px] font-black text-slate-600 uppercase tracking-widest">{method}</span>
                </div>
                <span className="text-[12px] font-black text-slate-900">{formatMoney(amount)}</span>
              </div>
            )) : <div className="text-center py-4 text-slate-300 text-[12px] font-black uppercase tracking-widest">Aggregating Channels...</div>}
          </div>
        </div>
      </section>

      {/* Transaction Summary Ledger */}
      <section className="overflow-hidden">
        <div className="px-2 py-6 md:py-8 flex flex-col gap-6">
          <div>
            <h3 className="text-lg md:text-xl font-black tracking-tight text-slate-900">Collection Ledger</h3>
            <p className="text-[12px] font-black text-slate-500 uppercase tracking-widest mt-1">Real-time approved & pending audit trail</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3 auto-rows-max">
            {/* Search */}
            <div className="relative sm:col-span-2 lg:col-span-2">
              <span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 text-lg">search</span>
              <input
                id="searchQuery"
                name="searchQuery"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-12 pr-6 py-3 bg-white border-none rounded-2xl text-xs font-bold w-full focus:ring-2 focus:ring-primary/10 shadow-sm"
                placeholder="Search by student or ID..."
                type="text"
              />
            </div>

            {/* Status Filter */}
            <select
              id="statusFilter"
              name="statusFilter"
              value={statusFilter}
              onChange={(e) => {
                setStatusFilter(e.target.value as PaymentStatus | '');
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            >
              <option value="">All Status</option>
              <option value="PENDING">Pending</option>
              <option value="APPROVED">Approved</option>
              <option value="REJECTED">Rejected</option>
            </select>

            {/* Method Filter */}
            <select
              id="methodFilter"
              name="methodFilter"
              value={methodFilter}
              onChange={(e) => {
                setMethodFilter(e.target.value);
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            >
              <option value="">All Methods</option>
              <option value="BANK">Bank</option>
              <option value="MOBILE_MONEY">Mobile Money</option>
              <option value="CASH">Cash</option>
              <option value="OTHER">Other</option>
            </select>

            {/* Start Date */}
            <input
              id="startDate"
              name="startDate"
              type="date"
              value={startDate}
              onChange={(e) => {
                setStartDate(e.target.value);
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            />

            {/* End Date */}
            <input
              id="endDate"
              name="endDate"
              type="date"
              value={endDate}
              onChange={(e) => {
                setEndDate(e.target.value);
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            />

            {/* Academic Year Filter */}
            <input
              id="academicYearFilter"
              name="academicYearFilter"
              placeholder="Academic Year (e.g. 2026)"
              value={academicYearFilter}
              onChange={(e) => {
                setAcademicYearFilter(e.target.value);
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            />

            {/* Term Filter */}
            <select
              id="termFilter"
              name="termFilter"
              value={termFilter}
              onChange={(e) => {
                setTermFilter(e.target.value);
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            >
              <option value="">All Terms</option>
              <option value="Term 1">Term 1</option>
              <option value="Term 2">Term 2</option>
              <option value="Term 3">Term 3</option>
            </select>

            {/* Semester Filter */}
            <select
              id="semesterFilter"
              name="semesterFilter"
              value={semesterFilter}
              onChange={(e) => {
                setSemesterFilter(e.target.value);
                setCurrentPage(1);
              }}
              className="px-4 py-3 bg-white border border-slate-200 rounded-2xl text-xs font-bold focus:ring-2 focus:ring-primary/10 shadow-sm"
            >
              <option value="">All Semesters</option>
              <option value="Semester 1">Semester 1</option>
              <option value="Semester 2">Semester 2</option>
            </select>

            {/* Clear Filters */}
            {(statusFilter || methodFilter || startDate || endDate || academicYearFilter || termFilter || semesterFilter || searchQuery) && (
              <div className="flex items-center gap-3">
                <button
                  onClick={() => {
                    setStatusFilter('');
                    setMethodFilter('');
                    setStartDate('');
                    setEndDate('');
                    setAcademicYearFilter('');
                    setTermFilter('');
                    setSemesterFilter('');
                    setSearchQuery('');
                    setCurrentPage(1);
                  }}
                  className="px-4 py-3 bg-slate-100 hover:bg-slate-200 rounded-2xl text-xs font-bold text-slate-600 transition-all whitespace-nowrap"
                >
                  Clear All
                </button>
                <button
                  onClick={handleExportRecentPayments}
                  className="px-4 py-3 bg-primary/5 hover:bg-primary text-primary hover:text-white rounded-2xl text-xs font-black uppercase tracking-widest transition-all flex items-center gap-2 border border-primary/20"
                >
                  <span className="material-symbols-outlined text-[16px]">file_export</span>
                  Export Result
                </button>
              </div>
            )}
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="text-[11px] font-black uppercase tracking-[0.2em] text-slate-500 bg-slate-50/20 border-b border-slate-50">
                <th className="px-2 py-5 font-black text-slate-500 uppercase tracking-widest text-[11px]">Timeline</th>
                <th className="px-4 py-5 font-black text-slate-500 uppercase tracking-widest text-[11px]">ID</th>
                <th className="px-4 py-5 font-black text-slate-500 uppercase tracking-widest text-[11px]">Student Name</th>
                <th className="px-4 py-5 font-black text-slate-500 uppercase tracking-widest text-[11px]">Method</th>
                <th className="px-4 py-5 font-black text-slate-500 uppercase tracking-widest text-[11px]">Amount (MWK)</th>
                {isAdmin && <th className="px-4 py-5 font-black text-primary uppercase tracking-widest text-[11px]">Audited By</th>}
                <th className="px-4 py-5 font-black text-slate-500 uppercase tracking-widest text-[11px]">Status</th>
                <th className="px-2 py-5 text-right font-black text-slate-500 uppercase tracking-widest text-[11px]">View</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {filteredPayments.length === 0 ? (
                <tr>
                  <td colSpan={isAdmin ? 9 : 8} className="px-2 py-20 text-center text-slate-300 font-black uppercase tracking-widest text-xs">No transactions recorded in current matrix.</td>
                </tr>
              ) : (
                filteredPayments.map((payment) => (
                  <tr key={payment.id} className="hover:bg-slate-50/50 transition-colors group">
                    <td className="px-2 py-6 text-[11px] font-bold text-slate-500">
                      {new Date(payment.submittedAt).toLocaleDateString()} · {new Date(payment.submittedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </td>
                    <td className="px-4 py-6 text-[12.5px] font-black text-slate-500 uppercase tracking-widest">#{payment.receiptNumber || 'LEGACY-TRX'}</td>
                    <td className="px-4 py-6">
                      <div className="text-sm font-black text-slate-900 tracking-tight">{payment.student?.firstName} {payment.student?.lastName}</div>
                      <div className="text-[11px] font-black text-slate-500 uppercase tracking-widest mt-1">{payment.student?.studentCode}</div>
                    </td>
                    <td className="px-4 py-6 font-black text-slate-600 uppercase text-[11px] tracking-widest">{payment.method}</td>
                    <td className="px-4 py-6 text-sm font-black text-slate-900">{formatMoney(payment.amount)}</td>
                    {isAdmin && (
                      <td className="px-4 py-6">
                        {payment.verifier && (
                          <div className="flex items-center gap-1.5 mb-1">
                            <span className="material-symbols-outlined text-[12px] text-emerald-500">verified_user</span>
                            <span className="text-[9px] font-black uppercase tracking-tighter text-slate-400">{payment.verifier.email.split('@')[0]}</span>
                          </div>
                        )}
                        {payment.reviewer && (
                          <div className="flex items-center gap-1.5">
                            <span className="material-symbols-outlined text-[12px] text-primary">policy</span>
                            <span className="text-[9px] font-black uppercase tracking-tighter text-slate-500">{payment.reviewer.email.split('@')[0]}</span>
                          </div>
                        )}
                        {!payment.verifier && !payment.reviewer && <span className="text-[9px] text-slate-300 italic">Unverified</span>}
                      </td>
                    )}
                    <td className="px-4 py-6">
                      <span className={`px-4 py-1.5 rounded-full text-[11px] font-black uppercase tracking-widest ${payment.status === 'APPROVED' ? 'bg-emerald-50 text-emerald-700' :
                        payment.status === 'PENDING' ? 'bg-orange-50 text-orange-700' : 'bg-rose-50 text-rose-700'
                        }`}>
                        {payment.status === 'APPROVED' ? 'Verified' : payment.status}
                      </span>
                      {payment.reviewNotes && (
                        <div className="text-[8px] text-slate-500 mt-1 italic max-w-xs">{payment.reviewNotes}</div>
                      )}
                    </td>
                    <td className="px-2 py-6 text-right text-slate-300 hover:text-primary transition-colors">
                      <span 
                        onClick={() => navigate(`/admin/payments/${payment.id}/audit`)}
                        className="material-symbols-outlined text-[18px] cursor-pointer"
                      >
                        visibility
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className="py-6 flex flex-col md:flex-row justify-between items-center gap-4 text-[12px] font-black uppercase tracking-widest text-slate-500">
          <span>Displaying {(report?.pagination?.offset ?? 0) + 1} to {Math.min((report?.pagination?.offset ?? 0) + (report?.pagination?.limit ?? 25), report?.pagination?.total ?? 0)} of {report?.pagination?.total ?? 0} journal entries</span>
          <div className="flex gap-2">
            <button
              onClick={() => setCurrentPage(Math.max(1, currentPage - 1))}
              disabled={currentPage === 1}
              className="p-2.5 hover:bg-slate-100 rounded-xl transition-all disabled:opacity-20"
            >
              <span className="material-symbols-outlined text-[18px]">chevron_left</span>
            </button>
            {Array.from({ length: Math.ceil((report?.pagination?.total ?? 0) / pageSize) }, (_, i) => i + 1).slice(0, 5).map((page) => (
              <button
                key={page}
                onClick={() => setCurrentPage(page)}
                className={`w-10 h-10 rounded-xl transition-all ${currentPage === page ? 'bg-slate-900 text-white shadow-lg shadow-slate-200' : 'hover:bg-white border border-slate-100'}`}
              >
                {page}
              </button>
            ))}
            {Math.ceil((report?.pagination?.total ?? 0) / pageSize) > 5 && (
              <>
                <span className="text-slate-300">...</span>
                <button
                  onClick={() => setCurrentPage(Math.ceil((report?.pagination?.total ?? 0) / pageSize))}
                  className={`w-10 h-10 rounded-xl transition-all ${currentPage === Math.ceil((report?.pagination?.total ?? 0) / pageSize) ? 'bg-slate-900 text-white shadow-lg shadow-slate-200' : 'hover:bg-white border border-slate-100'}`}
                >
                  {Math.ceil((report?.pagination?.total ?? 0) / pageSize)}
                </button>
              </>
            )}
            <button
              onClick={() => setCurrentPage(Math.min(Math.ceil((report?.pagination?.total ?? 0) / pageSize), currentPage + 1))}
              disabled={currentPage >= Math.ceil((report?.pagination?.total ?? 0) / pageSize)}
              className="p-2.5 hover:bg-white rounded-xl transition-all disabled:opacity-20 border border-slate-100"
            >
              <span className="material-symbols-outlined text-[18px]">chevron_right</span>
            </button>
          </div>
        </div>
      </section>

      {/* Official Snapshot History */}
      <section className="bg-slate-50/50 p-8 rounded-[3rem] border border-slate-100 overflow-hidden">
        <div className="flex justify-between items-end mb-8">
          <div>
            <h3 className="text-xl font-black tracking-tight text-slate-900">Institutional Audit History</h3>
            <p className="text-[12px] font-black text-slate-500 uppercase tracking-widest mt-1">Official archived snapshots and financial records</p>
          </div>
          <div className="bg-emerald-50 text-emerald-700 px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest border border-emerald-100">
            {history.length} Snapshots Saved
          </div>
        </div>

        <div className="overflow-hidden bg-white rounded-3xl border border-slate-100">
          <table className="w-full">
            <thead>
              <tr className="text-[11px] font-black uppercase tracking-[0.2em] text-slate-400 border-b border-slate-50">
                <th className="px-6 py-5 text-left">Generation Date</th>
                <th className="px-6 py-5 text-left">Internal Title</th>
                <th className="px-6 py-5 text-left">Authorized By</th>
                <th className="px-6 py-5 text-left">Type</th>
                <th className="px-6 py-5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {history.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-slate-300 italic font-black uppercase tracking-widest text-xs">No official snapshots in institutional archive.</td>
                </tr>
              ) : (
                history.map((snapshot) => (
                  <tr key={snapshot.id} className="hover:bg-slate-50/50 transition-all group">
                    <td className="px-6 py-6 text-sm font-bold text-slate-600">
                      {new Date(snapshot.createdAt).toLocaleString()}
                    </td>
                    <td className="px-6 py-6">
                      <div className="text-sm font-black text-slate-900">{snapshot.title}</div>
                      <div className="text-[10px] text-slate-400 mt-1 uppercase font-black tracking-widest">Fixed Audit Record</div>
                    </td>
                    <td className="px-6 py-6 font-black text-slate-600 text-xs uppercase tracking-tight">
                      {snapshot.user?.firstName} {snapshot.user?.lastName} (Finance)
                    </td>
                    <td className="px-6 py-6">
                      <span className="px-3 py-1 bg-slate-100 text-[10px] font-black uppercase tracking-widest rounded-lg text-slate-500">
                        {snapshot.reportType}
                      </span>
                    </td>
                    <td className="px-6 py-6 text-right">
                      <button 
                        onClick={() => downloadSnapshot(snapshot)}
                        className="p-2.5 bg-primary/5 hover:bg-primary text-primary hover:text-white rounded-xl transition-all active:scale-90"
                      >
                        <span className="material-symbols-outlined text-[20px]">download</span>
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
